[workspace]
resolver = "2"
members = [
    "models/hue",
    "graphs/lighting"
]

[workspace.dependencies]
async-graphql = "6.0.9"
async-graphql-poem = "6.0.9"
poem = "1.3.58"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }